<template><div><h1 id="концепции-vue-модулеи" tabindex="-1"><a class="header-anchor" href="#концепции-vue-модулеи"><span>Концепции Vue модулей</span></a></h1>
<h3 id="установка-компонентов" tabindex="-1"><a class="header-anchor" href="#установка-компонентов"><span>Установка компонентов</span></a></h3>
<p>В пакете не содержится общего плагина глобальной регистрации всех компонентов, поскольку из коробки они не являются готовыми. Их можно использовать со базовыми стилями прямо на экранах интерфейса, но рекомендуется всё же на их основе сделать свои компоненты, в которых уже можно изолировать и установить свой CSS для каждого элемента в компоненте.</p>
<blockquote>
<p>Стандартные стили компонентов написаны на <a href="https://vanilla-extract.style/" target="_blank" rel="noopener noreferrer">vanilla-extract</a>. Все модули css.ts также экспортируемы, поэтому при его использовании в проекте вам доступен <a href="https://vanilla-extract.style/documentation/style-composition" target="_blank" rel="noopener noreferrer">приём композиции</a> для расширения базовых стилей.</p>
</blockquote>
<p>Если ваш проект использует vanilla-extract или вам нужны базовые стили для превью компонентов blanc, добавьте их в точку входа:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="index.ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token string">'blanc-ui/vue/css'</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>Однако вы ничем не ограничены - можно применять CSS Modules, tailwind и вообще всё что захотите. Все свойства стилей и их вариантов - это обычные классы, то есть, строки.</p>
<h4 id="cоздание-кнопки-на-базе-blanc-ui-c-tailwindcss" tabindex="-1"><a class="header-anchor" href="#cоздание-кнопки-на-базе-blanc-ui-c-tailwindcss"><span>Cоздание кнопки на базе Blanc UI c tailwindcss:</span></a></h4>
<div class="language-vue line-numbers-mode" data-highlighter="prismjs" data-ext="vue" data-title="MyButton.vue"><pre v-pre><code><span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ts<span class="token punctuation">"</span></span> <span class="token attr-name">setup</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Button<span class="token punctuation">,</span> Icon <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'blanc-ui/vue'</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> type ButtonProps <span class="token punctuation">,</span> type IconProps <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'blanc-ui/vue/types'</span></span>
<span class="line"><span class="token keyword">const</span> <span class="token punctuation">{</span></span>
<span class="line">  size <span class="token operator">=</span> <span class="token string">'medium'</span><span class="token punctuation">,</span></span>
<span class="line">  variant <span class="token operator">=</span> <span class="token string">'primary'</span><span class="token punctuation">,</span></span>
<span class="line">  icon<span class="token punctuation">,</span></span>
<span class="line">  whenClick</span>
<span class="line"><span class="token punctuation">}</span> <span class="token operator">=</span> defineProps<span class="token operator">&lt;</span><span class="token punctuation">{</span></span>
<span class="line">  icon<span class="token operator">?</span><span class="token operator">:</span> IconProps<span class="token punctuation">[</span><span class="token string">'name'</span><span class="token punctuation">]</span></span>
<span class="line">  variant<span class="token operator">?</span><span class="token operator">:</span> <span class="token string">'primary'</span> <span class="token operator">|</span> <span class="token string">'outlined'</span></span>
<span class="line"><span class="token punctuation">}</span> <span class="token operator">&amp;</span> Omit<span class="token operator">&lt;</span>ButtonProps<span class="token punctuation">,</span> <span class="token string">'variant'</span><span class="token operator">>></span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Button</span></span>
<span class="line">    <span class="token attr-name">:style</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>`inline-flex items-center`<span class="token punctuation">"</span></span></span>
<span class="line">    <span class="token attr-name">:variants</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{</span>
<span class="line">      'primary': 'bg-blue-600 text-white hover:bg-blue-700',</span>
<span class="line">      'outlined': 'border border-gray-300 text-gray-700 hover:border-gray-400 hover:text-gray-800',</span>
<span class="line">      'small': 'py-1 px-2 text-sm',</span>
<span class="line">      'medium': 'py-1.5 px-2.5',</span>
<span class="line">      'large': 'py-2 px-3 text-lg'</span>
<span class="line">    }<span class="token punctuation">"</span></span></span>
<span class="line">    <span class="token attr-name">:size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>size<span class="token punctuation">"</span></span></span>
<span class="line">    <span class="token attr-name">:variant</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>variant<span class="token punctuation">"</span></span></span>
<span class="line">    <span class="token attr-name">:whenClick</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>whenClick<span class="token punctuation">"</span></span></span>
<span class="line">  <span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Icon</span> <span class="token attr-name">v-if</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>icon<span class="token punctuation">'</span></span> <span class="token attr-name">:name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>icon<span class="token punctuation">'</span></span> <span class="token attr-name">size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>small<span class="token punctuation">'</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>mr-2<span class="token punctuation">'</span></span> <span class="token punctuation">/></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>slot</span> <span class="token punctuation">/></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Button</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="установка-плагинов" tabindex="-1"><a class="header-anchor" href="#установка-плагинов"><span>Установка плагинов</span></a></h3>
<p>Так же как и компоненты, плагины абстрактны и устанавливаются по отдельности. Они могут работать необязательно с компонентами Blank UI. Вы можете с их помощью управлять любыми компонентами.</p>
<h4 id="пример-установки" tabindex="-1"><a class="header-anchor" href="#пример-установки"><span>Пример установки</span></a></h4>
<p>Для глобального провайда во всём проекте:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="index.ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ViewLayersPlugin <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'blanc-ui/vue'</span></span>
<span class="line"><span class="token operator">...</span></span>
<span class="line">Vue<span class="token punctuation">.</span><span class="token function">use</span><span class="token punctuation">(</span>ViewLayersPlugin<span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">...</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Если вы хотите ограничить видимость плагина:</p>
<div class="language-vue line-numbers-mode" data-highlighter="prismjs" data-ext="vue" data-title="MyAwesomePage.vue"><pre v-pre><code><span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ts<span class="token punctuation">"</span></span> <span class="token attr-name">setup</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> provide<span class="token punctuation">,</span> getCurrentInstance <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> EventBus<span class="token punctuation">,</span> $eventBus<span class="token punctuation">,</span> Notify<span class="token punctuation">,</span> $notify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'blanc-ui/vue'</span></span>
<span class="line">provide<span class="token operator">&lt;</span>EventBus<span class="token operator">></span><span class="token punctuation">(</span>$eventBus<span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">EventBus</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">provide<span class="token operator">&lt;</span>Notify<span class="token operator">></span><span class="token punctuation">(</span>$notify<span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">Notify</span><span class="token punctuation">(</span><span class="token function">getCurrentInstance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span><span class="token punctuation">></span></span></span>
<span class="line">  ...</span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>MyAwesomeComponent</span> <span class="token punctuation">/></span></span></span>
<span class="line">  ...</span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-vue line-numbers-mode" data-highlighter="prismjs" data-ext="vue" data-title="MyAwesomeComponent.vue"><pre v-pre><code><span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ts<span class="token punctuation">"</span></span> <span class="token attr-name">setup</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> inject <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span>$eventBus<span class="token punctuation">,</span> $notify <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'blanc-ui/vue'</span></span>
<span class="line"><span class="token keyword">const</span> eventBus <span class="token operator">=</span> inject<span class="token operator">&lt;</span>EventBus<span class="token operator">></span><span class="token punctuation">(</span>$eventBus<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">const</span> notify <span class="token operator">=</span> inject<span class="token operator">&lt;</span>Notify<span class="token operator">></span><span class="token punctuation">(</span>$notify<span class="token punctuation">)</span></span>
<span class="line"></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


